name: background_downloader
description: A multi-platform background file downloader and uploader. Define the task, enqueue and monitor progress

version: 8.9.4
repository: https://github.com/781flyingdutchman/background_downloader

environment:
  sdk: ^3.5.0
  flutter:  '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.2
  http: ^1.1.0
  path_provider: ^2.0.2
  path: ^1.8.1
  async: ^2.6.0
  mime: ^2.0.0
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: '>4.0.0 <6.0.0'
  mockito: ^5.0.17
  build_runner: ^2.4.13

platforms:
  android:
  ios:
  linux:
  macos:
  windows:


flutter:
  plugin:
    platforms:
      android:
        package: com.bbflight.background_downloader
        pluginClass: BDPlugin
      ios:
        pluginClass: BackgroundDownloaderPlugin
