name: file_downloader
description: A background file downloader for iOS and Android
version: 1.0.0
repository: https://github.com/781flyingdutchman/file_downloader

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  path_provider:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.bbflight.file_downloader
        pluginClass: FileDownloaderPlugin
      ios:
        pluginClass: FileDownloaderPlugin
